sig_homepage:
    path:     /
    defaults: { _controller: SigBundle:Siniu:index }

sig_authenticate:
    path:   /login
    defaults: { _controller: SigBundle:Siniu:login }

sig_connect:
    path: /authenticate
    defaults: { _controller: SigBundle:Siniu:connect }
    methods: [POST]

sig_generator:
    path:   /generator
    defaults: { _controller: SigBundle:Generator:make }

sig_create_signature:
    path:   /create
    defaults: { _controller: SigBundle:Form:index }